=== RMI/pbtar/src/schema/pathwayMetadata.v1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://pathways.rmi.org/schema/pathwayMetadata.v1.json",
  "title": "Pathway Metadata",
  "description": "A schema for the pathway metadata dataset in PBTAR.",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "URI of the schema that validates this document (see https://json-schema.org/).",
      "type": "string",
      "maxLength": 1000
    },
    "id": {
      "description": "The unique identifier for a pathway.",
      "type": "string",
      "maxLength": 100
    },
    "name": {
      "description": "Name of the pathway.",
      "$ref": "http://pathways.rmi.org/schema/common/label.v1.json",
      "tsType": "import('./common/label.v1').LabelV1"
    },
    "description": {
      "description": "Brief description of the pathway.",
      "type": "string",
      "pattern": "\\.$",
      "maxLength": 100
    },
    "publication": {
      "description": "Bibliographic information about the report or dataset.",
      "$ref": "http://pathways.rmi.org/schema/common/publication.v1.json",
      "tsType": "import('./common/publication.v1').PublicationV1"
    },
    "pathwayType": {
      "description": "Type of the pathway pathway.",
      "type": "string",
      "enum": ["Normative", "Exploratory", "Predictive"]
    },
    "modelYearNetzero": {
      "description": "Year by which net zero is reached in the pathway. If Pathway does not reach net zero, this field should be omitted.",
      "type": "integer",
      "minimum": 2030,
      "maximum": 2100
    },
    "modelYearStart": {
      "description": "Year from which the model starts.",
      "type": "integer",
      "minimum": 1900,
      "maximum": 2030
    },
    "modelYearEnd": {
      "description": "Year in which the model ends.",
      "type": "integer",
      "minimum": 2030,
      "maximum": 2100
    },
    "modelTempIncrease": {
      "description": "Modeled temperature increase expected by the pathway (in degrees Celsius).",
      "type": "number",
      "multipleOf": 0.1,
      "minimum": 0.5,
      "maximum": 3
    },
    "geography": {
      "description": "Geographical areas that the pathway covers.",
      "$ref": "http://pathways.rmi.org/schema/common/geography.v1.json",
      "tsType": "import('./common/geography.v1').GeographyV1"
    },
    "sectors": {
      "description": "Sectors that the pathway covers.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "$ref": "http://pathways.rmi.org/schema/common/sector.v1.json#/$defs/displayName"
          },
          "technologies": {
            "type": "array",
            "description": "Technologies applicable to this sector.",
            "items": {
              "$ref": "http://pathways.rmi.org/schema/common/technology.v1.json#/$defs/displayName"
            }
          }
        },
        "required": ["name", "technologies"],
        "additionalProperties": false
      }
    },
    "pathwayOverview": {
      "description": "Overview of the pathway.",
      "type": "string",
      "pattern": "\\.$",
      "maxLength": 1000
    },
    "expertOverview": {
      "description": "Expert recommendation for the pathway.",
      "type": "string",
      "pattern": "\\.$",
      "maxLength": 10000
    },
    "metric": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "$ref": "http://pathways.rmi.org/schema/common/metric.v1.json#/$defs/displayName",
        "tsType": "import('./common/metric.v1').MetricV1['displayName']"
      }
    },
    "keyFeatures": {
      "description": "Key features of the pathway.",
      "type": "object",
      "properties": {
        "emissionsTrajectory": {
          "description": "Describes the overall trend of greenhouse gas emissions over time, from continued growth to rapid decline.",
          "type": "string",
          "enum": [
            "No information",
            "Significant increase",
            "Moderate increase",
            "Minor increase",
            "Low or no change",
            "Minor decrease",
            "Moderate decrease",
            "Significant decrease"
          ]
        },
        "energyEfficiency": {
          "description": "Indicates how efficiently energy is used to produce economic output across the sectors covered in the pathway.",
          "type": "string",
          "enum": [
            "No information",
            "Significant deterioration",
            "Moderate deterioration",
            "Minor deterioration",
            "Low or no change",
            "Minor improvement",
            "Moderate improvement",
            "Significant improvement"
          ]
        },
        "energyDemand": {
          "description": "Captures the change in total energy consumption, driven by factors such as socio-economic development, technology shifts and consumer behavior.",
          "type": "string",
          "enum": [
            "No information",
            "Significant decrease",
            "Moderate decrease",
            "Minor decrease",
            "Low or no change",
            "Minor increase",
            "Moderate increase",
            "Significant increase"
          ]
        },
        "electrification": {
          "description": "Represents the extent to which energy end-uses transition from fossil fuels to electricity.",
          "type": "string",
          "enum": [
            "No information",
            "Significant decrease",
            "Moderate decrease",
            "Minor decrease",
            "Low or no change",
            "Minor increase",
            "Moderate increase",
            "Significant increase"
          ]
        },
        "policyTypes": {
          "description": "Identifies the types of policies modeled as drivers of the pathway, such as carbon pricing, subsidies, or mandated phaseouts of specific technologies.",
          "type": "array",
          "uniqueItems": true,
          "minItems": 1,
          "items": {
            "type": "string",
            "enum": [
              "Carbon price",
              "Feed-in tariffs",
              "Performance standards",
              "Phaseout dates",
              "Subsidies",
              "Target technology shares",
              "Other",
              "None"
            ]
          }
        },
        "technologyCostTrend": {
          "description": "Describes how technology costs evolve over time, from static cost assumptions to rapidly declining costs (e.g., via learning curves).",
          "type": "string",
          "enum": ["No information", "Increase", "Low or no change", "Decrease"]
        },
        "emissionsScope": {
          "$ref": "http://pathways.rmi.org/schema/common/emissionsScope.v1.json",
          "tsType": "import('./common/emissionsScope.v1').EmissionsScopeV1"
        },
        "policyAmbition": {
          "description": "Represents the overall stringency and intent of modeled policies relative to climate targets, often reflecting if and how far the included policies go beyond currently legislated ones",
          "type": "string",
          "enum": [
            "No information",
            "No policies included",
            "Current/legislated policies",
            "Current and drafted policies",
            "NDCs, unconditional only",
            "NDCs incl. conditional targets",
            "High ambition policies",
            "Other policy ambition"
          ]
        },
        "technologyCostsDetail": {
          "description": "Specifies the level of granularity in cost data, such as total system costs or detailed CAPEX/OPEX breakdowns.",
          "type": "string",
          "enum": [
            "No information",
            "Total costs",
            "Capital costs, O&M, etc.",
            "Other cost breakdown"
          ]
        },
        "newTechnologiesIncluded": {
          "description": "Lists emerging or breakthrough technologies that are explicitly modeled within the pathway. These are considered in technology deployment too.",
          "type": "array",
          "uniqueItems": true,
          "minItems": 1,
          "items": {
            "type": "string",
            "enum": [
              "No information",
              "No new technologies",
              "CCUS",
              "DAC",
              "Green H2/ammonia",
              "SAF",
              "Battery storage",
              "EGS/AGS",
              "Other new technologies"
            ]
          }
        },
        "investmentNeeds": {
          "description": "Summarizes how investment requirements are quantified, from total system to sector-level or supply-chain detail.",
          "type": "string",
          "enum": [
            "No information",
            "Total investment",
            "By sector",
            "By sector, part of value chain",
            "By technology",
            "By tech, part of value chain"
          ]
        }
      },
      "additionalProperties": false,
      "required": [
        "emissionsTrajectory",
        "energyEfficiency",
        "energyDemand",
        "electrification",
        "policyTypes",
        "technologyCostTrend",
        "emissionsScope",
        "policyAmbition",
        "technologyCostsDetail",
        "newTechnologiesIncluded",
        "investmentNeeds"
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "id",
    "name",
    "description",
    "publication",
    "pathwayType",
    "geography",
    "sectors",
    "expertOverview",
    "metric",
    "keyFeatures"
  ]
}

=== RMI/pbtar/src/data/iea/IEA-STEPS-2024.json
{
  "$schema": "http://pathways.rmi.org/schema/pathwayMetadata.v1.json",
  "id": "IEA-STEPS-2024",
  "publication": {
    "title": {
      "full": "World Energy Outlook 2024",
      "short": "WEO"
    },
    "publisher": {
      "full": "International Energy Agency",
      "short": "IEA"
    },
    "year": 2024,
    "city": "Paris",
    "license": "CC BY-NC-SA 4.0",
    "links": [
      {
        "description": "Report",
        "url": "https://www.iea.org/reports/world-energy-outlook-2024"
      },
      {
        "description": "Dataset",
        "url": "https://www.iea.org/data-and-statistics/data-product/world-energy-outlook-2024-free-dataset"
      }
    ]
  },
  "name": {
    "full": "Stated Policies Scenario",
    "short": "STEPS"
  },
  "description": "Global projection of current energy system trends and the impact of stated policies.",
  "geography": {
    "global": true,
    "regions": {
      "East Asia and Pacific": [],
      "Europe and Central Asia": [],
      "Latin America and Caribbean": [],
      "Middle East and North Africa": [],
      "North America": [],
      "South East Asia": [],
      "Sub-Saharan Africa": []
    },
    "country": ["US", "BR", "RU", "CN", "IN", "JP"]
  },
  "pathwayType": "Predictive",
  "modelTempIncrease": 2.4,
  "modelYearStart": 2023,
  "modelYearEnd": 2100,
  "sectors": [
    {
      "name": "Buildings",
      "technologies": []
    },
    {
      "name": "Steel",
      "technologies": []
    },
    {
      "name": "Cement",
      "technologies": []
    },
    {
      "name": "Chemicals",
      "technologies": []
    },
    {
      "name": "Coal Mining",
      "technologies": []
    },
    {
      "name": "Oil (Upstream)",
      "technologies": []
    },
    {
      "name": "Gas (Upstream)",
      "technologies": []
    },
    {
      "name": "Power",
      "technologies": [
        "Coal",
        "Oil",
        "Gas",
        "Nuclear",
        "Hydro",
        "Wind",
        "Solar",
        "Biomass",
        "Renewables",
        "Other"
      ]
    },
    {
      "name": "Automotive",
      "technologies": []
    },
    {
      "name": "Aviation",
      "technologies": []
    },
    {
      "name": "Shipping",
      "technologies": []
    },
    {
      "name": "Other",
      "technologies": []
    }
  ],
  "pathwayOverview": "The Stated Policies Scenario (STEPS) provides a sense of the energy sector’s direction of travel today, based on the latest market data, technology costs and in-depth analysis of the prevailing policy settings in countries around the world. STEPS is complemented by APS, a scenario which assumes that countries’ aspirational targets will be met in full. The difference between STEPS and APS highlights a commitment gap.",
  "expertOverview": "#### Pathway Description\n\nThe Stated Policies Scenario (STEPS) projects the energy sector’s current direction of travel, based on the latest market data, technology costs and in-depth analysis of the stated policies in countries around the world. STEPS provides a detailed projection of future outcomes based on current conditions, but does not attempt to predict which existing policies or economic conditions are more or less likely to change. The STEPS pathway corresponds to 2.4°C of warming by 2100 (50% probability). This is significantly higher than the IEA’s announced pledges scenario (APS), which projects 1.7°C of warming by 2100 (50% probability), and the IEA’s Net Zero scenario (NZE), which targets 1.5°C of warming by 2100 (50% probability).\n\n#### Core Drivers\n\nThe STEPS pathway is primarily driven by existing policy dynamics and forecast future declines in technology costs, which drive large-scale deployment of mature low-carbon technologies.\n\n*Policy:* The STEPS pathway models stated policies, such as energy subsidies or power development plans, but does not include aspirational policy goals that lack specific provisions for their implementation, such as long-term net-zero pledges. The STEPS pathway includes only existing or scheduled carbon pricing schemes for electricity, industry, and energy production sectors, and does not introduce a global carbon price, as is done in the APS and NZE pathway.\n\n*Technology costs:* Depending on the region, the IEA STEPS assumes moderate to significant cost declines in solar PV, onshore wind, and offshore wind power generation and modest cost declines in nuclear power generation. These declines are mostly driven by falling capital costs. The pathway projects moderate increases in fossil fuel power generation costs in advanced economies, but mixed trends in EMDEs. \n\nThe STEPS pathway provides detailed projections for demand shifts, infrastructure buildout, investment flows, and new technology deployment, but these factors are primarily caused by modelled existing policies and declining technology costs.  \n\n#### Application to Transition Assessment\n\nAs a predictive pathway based on detailed modeling of current stated policies, market conditions, and technology trends, STEPS provides a valuable base-case projection for benchmarking the impact of future transition impacts in the absence of significant policy or market shifts. As a global integrated assessment model, STEPS provides a direct connection between the described pathway and a global temperature outcome. While this allows assessing the ambition of stated targets or plans against a 2.4°C outcome, this high level of implied temperature rise is not applicable for most institutional targets.\n\nDue to its strong focus on modeling existing policy and market trends, STEPS is well-suited to assessing the alignment of corporate targets, plans, and investment pipelines against a conservative forecast of market shifts. Misalignment to the STEPS pathway indicates that a company or plan may already be lagging forecasted rates of change, potentially exposing them to regulatory risks or declining market share as other segments of the energy sector grow. As STEPS only models stated policies with clear implementation plans, and does not include aspirational pledges such as those modeled in APS, it can be viewed as a conservative projection of potential market dynamics, and plans that exceed the rate of transition forecast in STEPS may still be exposed to future risks if new policies or technology shifts occur.\n\nSTEPS provides benchmark data on 5- and 10-year intervals and uses a moderately detailed breakdown of specific generation technologies such as coal, onshore wind, offshore wind, solar PV, and geothermal. This level of detail makes it well-suited to assessing specific decarbonization levers and project pipelines within company plans. However, STEPS provides data at only the regional level. This limits its suitability for assessing companies which have operations concentrated in one or few countries, as it allows comparison only to the regional average.",
  "metric": [
    "Emissions Intensity",
    "Capacity",
    "Generation",
    "Technology Mix",
    "Absolute Emissions"
  ],
  "keyFeatures": {
    "emissionsTrajectory": "Minor decrease",
    "energyEfficiency": "Moderate improvement",
    "energyDemand": "Moderate increase",
    "electrification": "Moderate increase",
    "policyTypes": [
      "Carbon price",
      "Phaseout dates",
      "Subsidies",
      "Target technology shares",
      "Performance standards",
      "Other"
    ],
    "technologyCostTrend": "Decrease",
    "emissionsScope": "CO2",
    "policyAmbition": "Current and drafted policies",
    "technologyCostsDetail": "Capital costs, O&M, etc.",
    "newTechnologiesIncluded": [
      "CCUS",
      "DAC",
      "Green H2/ammonia",
      "SAF",
      "Battery storage"
    ],
    "investmentNeeds": "By tech, part of value chain"
  }
}

=== RMI/pbtar/src/data/transitionzero/TZ-BAU-2024.json
{
  "$schema": "http://pathways.rmi.org/schema/pathwayMetadata.v1.json",
  "id": "TZ-BAU-2024",
  "publication": {
    "title": {
      "full": "From Vision to Voltage"
    },
    "subtitle": "Open Access Modelling of the ASEAN Power Grid with TZ-APG",
    "author": [
      "Vu, T.",
      "Shivakumar, A.",
      "Suarez, I.",
      "Puspitarini, H. D.",
      "Majid, A."
    ],
    "publisher": {
      "full": "TransitionZero"
    },
    "year": 2024,
    "month": 12,
    "day": 2,
    "license": "CC BY 4.0",
    "links": [
      {
        "url": "https://blog.transitionzero.org/hubfs/Analysis/TZ-APG/TZ-APG%20-%20From%20Vision%20to%20Voltage%20-%20Report.pdf",
        "description": "Report"
      },
      {
        "description": "Technical Annex",
        "url": "https://blog.transitionzero.org/hubfs/Analysis/TZ-APG/tz-apg_technical-annex.pdf"
      },
      {
        "description": "Dataset",
        "url": "https://www.transitionzero.org/products/tz-asean-power-grid-model"
      }
    ]
  },
  "name": {
    "full": "Business as Usual",
    "short": "BAU"
  },
  "description": "Business-as-usual continuation of existing ASEAN power and transmission systems.",
  "geography": {
    "regions": {
      "South East Asia": []
    },
    "country": ["BN", "KH", "ID", "LA", "MY", "MN", "PH", "SG", "TH", "VN"]
  },
  "pathwayType": "Predictive",
  "modelYearStart": 2024,
  "modelYearEnd": 2035,
  "sectors": [
    {
      "name": "Power",
      "technologies": []
    }
  ],
  "expertOverview": "#### Pathway Description\n\nThe Business-as-Usual (BAU) scenario in TransitionZero’s TZ-APG v1 model depicts the ASEAN region’s power system as it operates under prevailing infrastructure and national policy conditions through 2035. Built on the PyPSA modeling framework, this scenario assumes all existing domestic and cross-border transmission lines remain in place with their present capacities, and no new interconnectors are added. The pathway thus mirrors the current structural reality of the ASEAN Power Grid.\n\nUnder the static grid environment in BAU, each country continues to meet rising demand primarily through national generation expansion rather than regional power exchange. Power flows remain unidirectional and modest, constrained by limited physical connectivity and the lack of integrated market frameworks. The scenario also maintains a conservative technology palette (coal, gas, hydropower, solar, and wind) consistent with current ASEAN deployment trends. \n\nA distinctive feature of TZ-APG v1 is that capacity and generation outcomes by 2035 vary only marginally across all four grid pathways. This underscores that the central focus of this study is not on changing generation composition but on understanding how different grid architectures affect system operation, investment distribution, and interregional dynamics. In BAU, this manifests as limited regional trade potential and continued reliance on domestic fossil resources.\n\n#### Core Drivers\n\nThe BAU pathway is driven by existing policy environments, continued demand growth, and limited grid investments.\n\n*Policy:* The BAU scenario reflects each country’s existing policy and capacity commitments as of 2023, incorporating renewable energy and emissions targets only insofar as they are already legislated. No new regional initiatives are included.\n\n*Technology:* The generation mix is dominated by coal, gas, and hydropower, with incremental renewable growth. The technology palette mirrors regional norms, meaning no carbon capture, nuclear, or ammonia co-firing developments are considered.\n\n*Demand shifts, infrastructure build-out, investment, and technology deployment:* Electricity demand follows policy-based compound annual growth rates, averaging 3–8% across countries, reflecting historical and planned growth trajectories. Transmission investment is minimal, focused on maintenance of existing assets. System expansion relies heavily on gas and coal additions within national boundaries.\n\n#### Application to Transition Assessment\n\nThe BAU scenario serves as the reference baseline for assessing ASEAN’s power system under static grid conditions. It represents the “current trajectory” case against which all other grid-expansion scenarios are compared. It is most suitable for comparing transition impacts of grid expansion and for understanding fossil fuel persistence in a non-interconnected region.\n\nBecause system-wide generation and capacity are consistent across all four TZ-APG scenarios, BAU primarily illustrates a regional energy system with no additional transmission flexibility. However, BAU has limited relevance for assessing target ambition or alignment with long-term transition goals. Since the model assumes minimal transformation of system structure, it does not represent a decarbonization trajectory but rather a structural baseline. It serves best as a contextual reference to measure the incremental value of grid cooperation and to interpret future system cost reductions or emissions savings achieved under more connected scenarios.\n\nThe BAU pathway provides capacity and generation data with limited time availability, providing only baseline 2023 and 2035 projections. It uses a moderately detailed breakdown by generation source, such as coal, solar, and wind. BAU provides both regional and country-specific results, allowing granular comparisons for companies operating across multiple countries. TransitionZero offers open access to its underlying TZ-APG model, providing significantly greater detail and customizability for users who are interested in more complex applications.",
  "metric": [
    "Emissions Intensity",
    "Absolute Emissions",
    "Capacity",
    "Generation",
    "Technology Mix"
  ],
  "keyFeatures": {
    "emissionsTrajectory": "No information",
    "energyEfficiency": "No information",
    "energyDemand": "No information",
    "electrification": "No information",
    "policyTypes": ["Target technology shares"],
    "technologyCostTrend": "Low or no change",
    "emissionsScope": "CO2e (unspecified GHGs)",
    "policyAmbition": "Current/legislated policies",
    "technologyCostsDetail": "Capital costs, O&M, etc.",
    "newTechnologiesIncluded": ["Battery storage"],
    "investmentNeeds": "No information"
  }
}

=== RMI/pbtar/src/data/un-sdsn-cw/SDSN-CW-OEP-LA-2025.json
{
  "$schema": "http://pathways.rmi.org/schema/pathwayMetadata.v1.json",
  "id": "SDSN-CW-OEP-LA-2025",
  "publication": {
    "title": {
      "full": "ASEAN Green Future Project Phase 2.2 Report, Optimization of Laos's Power Generation Sector"
    },
    "author": [
      "Phouphet Kyophilavong",
      "Phongsili Soukchalern",
      "Thanouxay Volavong",
      "Vonethaly Vongsavanthong"
    ],
    "publisher": {
      "full": "Sustainable Development Solutions Network and ClimateWorks Centre",
      "short": "UN SDSN, CW"
    },
    "year": 2025,
    "month": 2,
    "links": [
      {
        "description": "Report",
        "url": "https://files.unsdsn.org/AGF%20-%20Laos%202.2%20Report%20-%20release.pdf"
      }
    ]
  },
  "name": {
    "full": "Optimized Existing Policy Scenario LA",
    "short": "OEP LA"
  },
  "description": "Cost-optimized pathway under current policies with coal and hydropower expansion.",
  "geography": {
    "country": ["LA"]
  },
  "pathwayType": "Exploratory",
  "modelYearStart": 2020,
  "modelYearEnd": 2050,
  "sectors": [
    {
      "name": "Power",
      "technologies": ["Coal", "Hydro", "Solar", "Wind", "Biomass"]
    }
  ],
  "expertOverview": "#### Pathway Description\n\nThe Optimized Existing Policy scenario models Laos’s power and energy systems using the Low Emissions Analysis Platform (LEAP) under the ASEAN Green Future (AGF) project. The Optimized Existing Policy (OEP) scenario applies a market-optimal lens to the same policy context as the Existing Policy scenario, but it removes the policy-prescribed constraints on the power generation mix and optimizes for minimum system cost while still satisfying energy demand growth under existing policies. Under this scenario, the result is a more carbon-intensive but economically efficient variant of the Existing Policy pathway. \n\nNotably, total electricity generation in this scenario far exceeds that in the baseline, as the model maximizes Laos’s low-cost resources (especially hydropower) to produce as much power as needed at the lowest cost. By 2050, annual generation is 132.8 TWh in the OEP scenario, compared to only 57.3 TWh under the baseline, despite having the same installed capacity, indicating much higher utilization rates. \n\n#### Core Drivers\n\nThe OEP pathway is driven by cost optimization under market conditions with limited policy intervention. \n\n*Cost optimization:* Economic optimization is the defining driver of this scenario. It determines the cheapest mix of generation to meet electricity demand, without introducing any new climate constraints. This means that capital and operating costs dictate the outcome, and as such no additional renewables beyond those already mandated by policy are built unless they are cost-competitive.\n\n*Technology deployment:* Hydropower experiences large-scale expansions similar to those in the Existing Policy scenario. With no carbon price or emissions cap, coal-fired power remains in the mix as a low-cost source for baseload and export. The model keeps coal capacity at 4 GW through 2050, but generation is slightly higher in this scenario, resulting in higher power sector emissions in 2050 than in the Existing Policy scenario.\n\n#### Application to Transition Assessment\n\nAs a cost-optimized extension of the Existing Policy scenario, the Optimized Existing Policy scenario serves as a useful baseline for climate transition analysis. It represents a potential business-as-usual trajectory in which Laos’s power sector follows the present policy path without any new climate interventions. The OEP scenario offers a conservative planning case that helps financial actors understand the outcomes of current policies in Laos, which is useful for benchmarking. It also shows that significant emissions reductions are not a given without additional incentives or actions.\n\nDue to its focus on modeling cost optimization within existing policy, the OEP scenario is well-suited to assessing the alignment of corporate targets, plans, and investment pipelines against a cost-driven forecast of country-specific market shifts. Misalignment with the pathway indicates that a company or plan may already be lagging behind potential rates of change, potentially exposing it to regulatory risks or declining market share as other segments of the energy sector grow. Because the pathway includes a strong focus on cost optimization, it is a useful candidate for contextualizing the commercial and technical feasibility of transition strategies under the aggressive least-cost parameters described by the OEP pathway. Strategies that exceed the pace of change forecast under OEP may imply reliance on future policy or technology shifts. \n\nThe OEP pathway models power and energy systems to 2050, providing country-level projections for generation and capacity at 10-year intervals, with a high-level breakdown by energy source such as coal, gas, and renewables. Due to its country-specific nature, the OEP pathway has limited applicability to companies with operations across multiple geographies, but it offers greater detail and specificity for companies in Laos, as compared to global or regional pathways.",
  "metric": ["Absolute Emissions", "Capacity", "Generation", "Technology Mix"],
  "keyFeatures": {
    "emissionsTrajectory": "Significant increase",
    "energyEfficiency": "No information",
    "energyDemand": "No information",
    "electrification": "Moderate increase",
    "policyTypes": ["Target technology shares"],
    "technologyCostTrend": "Decrease",
    "emissionsScope": "CO2e (Kyoto)",
    "policyAmbition": "Current/legislated policies",
    "technologyCostsDetail": "Total costs",
    "newTechnologiesIncluded": ["No information"],
    "investmentNeeds": "Total investment"
  }
}
